type EntityStateFrames = Record<string, any>;

export enum EntityNameEnum {
  hero = "hero",
  wizard2 = "wizard2",
  huntress = "huntress",
  wizard1 = "wizard1",
  fallen = "fallen",
  // bandit1 = "bandit1",
  knight = "knight",
  // bandit2 = "bandit2",
  outdes = "outdes",
  samurai = "samurai",
  wizard3 = "wizard3",
  worm = "worm",
}

export const EntityName = {
  hero: "Hero Knight",
  wizard2: "Fire Wizard",
  huntress: "Enchan Shadow",
  wizard1: "Dark Wizard",
  fallen: "Spark Willow",
  bandit1: "Bandit Boss",
  knight: "St. Anderson",
  bandit2: "Hunter Scar",
  outdes: "Outworld Destroyer",
  samurai: "Miyamoto Musashi",
  wizard3: "Gandalf",
  worm: "Venomancer",
};

const EntityInventory: Record<string, EntityStateFrames> = {
  hero: {
    ATK1: require("@/assets/entities/hero/atk-1.gif"),
    ATK2: require("@/assets/entities/hero/atk-2.gif"),
    ATK3: require("@/assets/entities/hero/atk-3.gif"),
    Idle: require("@/assets/entities/hero/idle.gif"),
    Death: require("@/assets/entities/hero/death-0.gif"),
    Hurt: require("@/assets/entities/hero/hurt.gif"),
  },
  wizard2: {
    ATK1: require("@/assets/entities/wizard_2/EVil_Wizard_Attack.gif"),
    ATK2: require("@/assets/entities/wizard_2/EVil_Wizard_Attack.gif"),
    ATK3: require("@/assets/entities/wizard_2/EVil_Wizard_Attack.gif"),
    Idle: require("@/assets/entities/wizard_2/EVil_Wizard_Idle.gif"),
    Death: require("@/assets/entities/wizard_2/EVil_Wizard_Death.gif"),
    Hurt: require("@/assets/entities/wizard_2/EVil_Wizard_Hurt.gif"),
  },
  huntress: {
    ATK1: require("@/assets/entities/Blind_Huntress/atk_1.gif"),
    ATK2: require("@/assets/entities/Blind_Huntress/atk_1.gif"),
    ATK3: require("@/assets/entities/Blind_Huntress/atk_1.gif"),
    Idle: require("@/assets/entities/Blind_Huntress/idle.gif"),
    Death: require("@/assets/entities/Blind_Huntress/death.gif"),
    Hurt: require("@/assets/entities/Blind_Huntress/hurt.gif"),
  },
  wizard1: {
    ATK1: require('@/assets/entities/EVil_Wizard/atk_1.gif'),
    ATK2: require('@/assets/entities/EVil_Wizard/atk_1.gif'),
    ATK3: require('@/assets/entities/EVil_Wizard/atk_1.gif'),
    Idle: require('@/assets/entities/EVil_Wizard/idle.gif'),
    Death: require('@/assets/entities/EVil_Wizard/death.gif'),
    Hurt: require('@/assets/entities/EVil_Wizard/hurt.gif'),
  },
  fallen: {
    ATK1: require('@/assets/entities/FallenOrder/atk_1.gif'),
    ATK2: require('@/assets/entities/FallenOrder/atk_1.gif'),
    ATK3: require('@/assets/entities/FallenOrder/atk_1.gif'),
    Idle: require('@/assets/entities/FallenOrder/idle.gif'),
    Death: require('@/assets/entities/FallenOrder/death.gif'),
    Hurt: require('@/assets/entities/FallenOrder/hurt.gif'),
  },
  bandit1: {
    ATK1: require('@/assets/entities/Heavy_Bandit/atk_1.gif'),
    ATK2: require('@/assets/entities/Heavy_Bandit/atk_1.gif'),
    ATK3: require('@/assets/entities/Heavy_Bandit/atk_1.gif'),
    Idle: require('@/assets/entities/Heavy_Bandit/idle.gif'),
    Death: require('@/assets/entities/Heavy_Bandit/death.gif'),
    Hurt: require('@/assets/entities/Heavy_Bandit/hurt.gif'),
  },
  knight: {
    ATK1: require('@/assets/entities/Hero_Knight/atk_1.gif'),
    ATK2: require('@/assets/entities/Hero_Knight/atk_1.gif'),
    ATK3: require('@/assets/entities/Hero_Knight/atk_1.gif'),
    Idle: require('@/assets/entities/Hero_Knight/idle.gif'),
    Death: require('@/assets/entities/Hero_Knight/death.gif'),
    Hurt: require('@/assets/entities/Hero_Knight/hurt.gif'),
  },
  bandit2: {
    ATK1: require('@/assets/entities/Light_Bandit/atk_1.gif'),
    ATK2: require('@/assets/entities/Light_Bandit/atk_1.gif'),
    ATK3: require('@/assets/entities/Light_Bandit/atk_1.gif'),
    Idle: require('@/assets/entities/Light_Bandit/idle.gif'),
    Death: require('@/assets/entities/Light_Bandit/death.gif'),
    Hurt: require('@/assets/entities/Light_Bandit/hurt.gif'),
  },
  outdes: {
    ATK1: require('@/assets/entities/Luneblade/atk_1.gif'),
    ATK2: require('@/assets/entities/Luneblade/atk_1.gif'),
    ATK3: require('@/assets/entities/Luneblade/atk_1.gif'),
    Idle: require('@/assets/entities/Luneblade/idle.gif'),
    Death: require('@/assets/entities/Luneblade/death.gif'),
    Hurt: require('@/assets/entities/Luneblade/hurt.gif'),
  },
  samurai: {
    ATK1: require('@/assets/entities/Martial_Hero/atk_1.gif'),
    ATK2: require('@/assets/entities/Martial_Hero/atk_1.gif'),
    ATK3: require('@/assets/entities/Martial_Hero/atk_1.gif'),
    Idle: require('@/assets/entities/Martial_Hero/idle.gif'),
    Death: require('@/assets/entities/Martial_Hero/death.gif'),
    Hurt: require('@/assets/entities/Martial_Hero/hurt.gif'),
  },
  wizard3: {
    ATK1: require('@/assets/entities/Wizard_Pack/atk_1.gif'),
    ATK2: require('@/assets/entities/Wizard_Pack/atk_1.gif'),
    ATK3: require('@/assets/entities/Wizard_Pack/atk_1.gif'),
    Idle: require('@/assets/entities/Wizard_Pack/idle.gif'),
    Death: require('@/assets/entities/Wizard_Pack/death.gif'),
    Hurt: require('@/assets/entities/Wizard_Pack/hurt.gif'),
  },
  worm: {
    ATK1: require('@/assets/entities/Worm/atk_1.gif'),
    ATK2: require('@/assets/entities/Worm/atk_1.gif'),
    ATK3: require('@/assets/entities/Worm/atk_1.gif'),
    Idle: require('@/assets/entities/Worm/idle.gif'),
    Death: require('@/assets/entities/Worm/death.gif'),
    Hurt: require('@/assets/entities/Worm/hurt.gif'),
  },
};

export default EntityInventory;
