import { ImageSourcePropType } from "react-native";

// Gem enum
export enum GemNameEnum {
  Cluster_Blue = "Cluster_Blue",
  Cluster_Dark_Blue = "Cluster_Dark_Blue",
  Cluster_Gold = "Cluster_Gold",
  Cluster_Light_Green = "Cluster_Light_Green",
  Cluster_Lilac = "Cluster_Lilac",
  Cluster_Purple = "Cluster_Purple",
  Cluster_Red = "Cluster_Red",
  Cluster_Turquoise = "Cluster_Turquoise",
  Crystal_Blue = "Crystal_Blue",
  Crystal_Dark_Blue = "Crystal_Dark_Blue",
  Crystal_Gold = "Crystal_Gold",
  Crystal_Light_Green = "Crystal_Light_Green",
  Crystal_Lilac = "Crystal_Lilac",
  Crystal_Purple = "Crystal_Purple",
  Crystal_Red = "Crystal_Red",
  Crystal_Turquoise = "Crystal_Turquoise",
  Hexa_Blue = "Hexa_Blue",
  Hexa_Dark_Blue = "Hexa_Dark_Blue",
  Hexa_Gold = "Hexa_Gold",
  Hexa_Light_Green = "Hexa_Light_Green",
  Hexa_Lilac = "Hexa_Lilac",
  Hexa_Purple = "Hexa_Purple",
  Hexa_Red = "Hexa_Red",
  Hexa_Turquoise = "Hexa_Turquoise",
  Jewel_Blue = "Jewel_Blue",
  Jewel_Dark_Blue = "Jewel_Dark_Blue",
  Jewel_Gold = "Jewel_Gold",
  Jewel_Light_Green = "Jewel_Light_Green",
  Jewel_Lilac = "Jewel_Lilac",
  Jewel_Purple = "Jewel_Purple",
  Jewel_Red = "Jewel_Red",
  Jewel_Turquoise = "Jewel_Turquoise",
  Obelisk_Blue = "Obelisk_Blue",
  Obelisk_Dark_Blue = "Obelisk_Dark_Blue",
  Obelisk_Gold = "Obelisk_Gold",
  Obelisk_Light_Green = "Obelisk_Light_Green",
  Obelisk_Lilac = "Obelisk_Lilac",
  Obelisk_Purple = "Obelisk_Purple",
  Obelisk_Red = "Obelisk_Red",
  Obelisk_Turquoise = "Obelisk_Turquoise",
  Orb_Blue = "Orb_Blue",
  Orb_Dark_Blue = "Orb_Dark_Blue",
  Orb_Gold = "Orb_Gold",
  Orb_Light_Green = "Orb_Light_Green",
  Orb_Lilac = "Orb_Lilac",
  Orb_Purple = "Orb_Purple",
  Orb_Red = "Orb_Red",
  Orb_Turquoise = "Orb_Turquoise",
  Prism_Blue = "Prism_Blue",
  Prism_Dark_Blue = "Prism_Dark_Blue",
  Prism_Gold = "Prism_Gold",
  Prism_Light_Green = "Prism_Light_Green",
  Prism_Lilac = "Prism_Lilac",
  Prism_Purple = "Prism_Purple",
  Prism_Red = "Prism_Red",
  Prism_Turquoise = "Prism_Turquoise",
  Shard_Blue = "Shard_Blue",
  Shard_Dark_Blue = "Shard_Dark_Blue",
  Shard_Gold = "Shard_Gold",
  Shard_Light_Green = "Shard_Light_Green",
  Shard_Lilac = "Shard_Lilac",
  Shard_Purple = "Shard_Purple",
  Shard_Red = "Shard_Red",
  Shard_Turquoise = "Shard_Turquoise",
}

// Gem assets record
export const GemAssets: Record<GemNameEnum, ImageSourcePropType> = {
  [GemNameEnum.Cluster_Blue]: require("@/assets/gems/Cluster_Blue.gif"),
  [GemNameEnum.Cluster_Dark_Blue]: require("@/assets/gems/Cluster_Dark_Blue.gif"),
  [GemNameEnum.Cluster_Gold]: require("@/assets/gems/Cluster_Gold.gif"),
  [GemNameEnum.Cluster_Light_Green]: require("@/assets/gems/Cluster_Light_Green.gif"),
  [GemNameEnum.Cluster_Lilac]: require("@/assets/gems/Cluster_Lilac.gif"),
  [GemNameEnum.Cluster_Purple]: require("@/assets/gems/Cluster_Purple.gif"),
  [GemNameEnum.Cluster_Red]: require("@/assets/gems/Cluster_Red.gif"),
  [GemNameEnum.Cluster_Turquoise]: require("@/assets/gems/Cluster_Turquoise.gif"),
  [GemNameEnum.Crystal_Blue]: require("@/assets/gems/Crystal_Blue.gif"),
  [GemNameEnum.Crystal_Dark_Blue]: require("@/assets/gems/Crystal_Dark_Blue.gif"),
  [GemNameEnum.Crystal_Gold]: require("@/assets/gems/Crystal_Gold.gif"),
  [GemNameEnum.Crystal_Light_Green]: require("@/assets/gems/Crystal_Light_Green.gif"),
  [GemNameEnum.Crystal_Lilac]: require("@/assets/gems/Crystal_Lilac.gif"),
  [GemNameEnum.Crystal_Purple]: require("@/assets/gems/Crystal_Purple.gif"),
  [GemNameEnum.Crystal_Red]: require("@/assets/gems/Crystal_Red.gif"),
  [GemNameEnum.Crystal_Turquoise]: require("@/assets/gems/Crystal_Turquoise.gif"),
  [GemNameEnum.Hexa_Blue]: require("@/assets/gems/Hexa_Blue.gif"),
  [GemNameEnum.Hexa_Dark_Blue]: require("@/assets/gems/Hexa_Dark_Blue.gif"),
  [GemNameEnum.Hexa_Gold]: require("@/assets/gems/Hexa_Gold.gif"),
  [GemNameEnum.Hexa_Light_Green]: require("@/assets/gems/Hexa_Light_Green.gif"),
  [GemNameEnum.Hexa_Lilac]: require("@/assets/gems/Hexa_Lilac.gif"),
  [GemNameEnum.Hexa_Purple]: require("@/assets/gems/Hexa_Purple.gif"),
  [GemNameEnum.Hexa_Red]: require("@/assets/gems/Hexa_Red.gif"),
  [GemNameEnum.Hexa_Turquoise]: require("@/assets/gems/Hexa_Turquoise.gif"),
  [GemNameEnum.Jewel_Blue]: require("@/assets/gems/Jewel_Blue.gif"),
  [GemNameEnum.Jewel_Dark_Blue]: require("@/assets/gems/Jewel_Dark_Blue.gif"),
  [GemNameEnum.Jewel_Gold]: require("@/assets/gems/Jewel_Gold.gif"),
  [GemNameEnum.Jewel_Light_Green]: require("@/assets/gems/Jewel_Light_Green.gif"),
  [GemNameEnum.Jewel_Lilac]: require("@/assets/gems/Jewel_Lilac.gif"),
  [GemNameEnum.Jewel_Purple]: require("@/assets/gems/Jewel_Purple.gif"),
  [GemNameEnum.Jewel_Red]: require("@/assets/gems/Jewel_Red.gif"),
  [GemNameEnum.Jewel_Turquoise]: require("@/assets/gems/Jewel_Turquoise.gif"),
  [GemNameEnum.Obelisk_Blue]: require("@/assets/gems/Obelisk_Blue.gif"),
  [GemNameEnum.Obelisk_Dark_Blue]: require("@/assets/gems/Obelisk_Dark_Blue.gif"),
  [GemNameEnum.Obelisk_Gold]: require("@/assets/gems/Obelisk_Gold.gif"),
  [GemNameEnum.Obelisk_Light_Green]: require("@/assets/gems/Obelisk_Light_Green.gif"),
  [GemNameEnum.Obelisk_Lilac]: require("@/assets/gems/Obelisk_Lilac.gif"),
  [GemNameEnum.Obelisk_Purple]: require("@/assets/gems/Obelisk_Purple.gif"),
  [GemNameEnum.Obelisk_Red]: require("@/assets/gems/Obelisk_Red.gif"),
  [GemNameEnum.Obelisk_Turquoise]: require("@/assets/gems/Obelisk_Turquoise.gif"),
  [GemNameEnum.Orb_Blue]: require("@/assets/gems/Orb_Blue.gif"),
  [GemNameEnum.Orb_Dark_Blue]: require("@/assets/gems/Orb_Dark_Blue.gif"),
  [GemNameEnum.Orb_Gold]: require("@/assets/gems/Orb_Gold.gif"),
  [GemNameEnum.Orb_Light_Green]: require("@/assets/gems/Orb_Light_Green.gif"),
  [GemNameEnum.Orb_Lilac]: require("@/assets/gems/Orb_Lilac.gif"),
  [GemNameEnum.Orb_Purple]: require("@/assets/gems/Orb_Purple.gif"),
  [GemNameEnum.Orb_Red]: require("@/assets/gems/Orb_Red.gif"),
  [GemNameEnum.Orb_Turquoise]: require("@/assets/gems/Orb_Turquoise.gif"),
  [GemNameEnum.Prism_Blue]: require("@/assets/gems/Prism_Blue.gif"),
  [GemNameEnum.Prism_Dark_Blue]: require("@/assets/gems/Prism_Dark_Blue.gif"),
  [GemNameEnum.Prism_Gold]: require("@/assets/gems/Prism_Gold.gif"),
  [GemNameEnum.Prism_Light_Green]: require("@/assets/gems/Prism_Light_Green.gif"),
  [GemNameEnum.Prism_Lilac]: require("@/assets/gems/Prism_Lilac.gif"),
  [GemNameEnum.Prism_Purple]: require("@/assets/gems/Prism_Purple.gif"),
  [GemNameEnum.Prism_Red]: require("@/assets/gems/Prism_Red.gif"),
  [GemNameEnum.Prism_Turquoise]: require("@/assets/gems/Prism_Turquoise.gif"),
  [GemNameEnum.Shard_Blue]: require("@/assets/gems/Shard_Blue.gif"),
  [GemNameEnum.Shard_Dark_Blue]: require("@/assets/gems/Shard_Dark_Blue.gif"),
  [GemNameEnum.Shard_Gold]: require("@/assets/gems/Shard_Gold.gif"),
  [GemNameEnum.Shard_Light_Green]: require("@/assets/gems/Shard_Light_Green.gif"),
  [GemNameEnum.Shard_Lilac]: require("@/assets/gems/Shard_Lilac.gif"),
  [GemNameEnum.Shard_Purple]: require("@/assets/gems/Shard_Purple.gif"),
  [GemNameEnum.Shard_Red]: require("@/assets/gems/Shard_Red.gif"),
  [GemNameEnum.Shard_Turquoise]: require("@/assets/gems/Shard_Turquoise.gif"),
};
