import { ImageSourcePropType } from "react-native";

export enum InventoryCategoryEnum {
  weapon = "Weapon",
  shield = "Shield",
  body = "Body",
  head = "Head",
  jewelry = "Jewelry",
  leg = "Leg",
}

type InventoryAssetsType = Record<
  InventoryCategoryEnum,
  Record<string, ImageSourcePropType>
>;

export const InventoryAssets: InventoryAssetsType = {
  [InventoryCategoryEnum.weapon]: {
    Ancient: require("@/assets/inventories/weapons/Ancient.png"),
    Ceremony: require("@/assets/inventories/weapons/Ceremony.png"),
    Cursed_Relic: require("@/assets/inventories/weapons/Cursed_Relic.png"),
    Devine_Relic: require("@/assets/inventories/weapons/Devine_Relic.png"),
    Dragon_Slayer: require("@/assets/inventories/weapons/Dragon_Slayer.png"),
    Duel: require("@/assets/inventories/weapons/Duel.png"),
    Electric: require("@/assets/inventories/weapons/Electric.png"),
    Elegant: require("@/assets/inventories/weapons/Elegant.png"),
    Fire: require("@/assets/inventories/weapons/Fire.png"),
    Flower: require("@/assets/inventories/weapons/Flower.png"),
    Glowing: require("@/assets/inventories/weapons/Glowing.png"),
    Guardian: require("@/assets/inventories/weapons/Guardian.png"),
    Ice: require("@/assets/inventories/weapons/Ice.png"),
    Magic: require("@/assets/inventories/weapons/Magic.png"),
    Many: require("@/assets/inventories/weapons/Many.png"),
    Moon: require("@/assets/inventories/weapons/Moon.png"),
    Poisonous: require("@/assets/inventories/weapons/Poisonous.png"),
    Powerful: require("@/assets/inventories/weapons/Powerful.png"),
    Royal: require("@/assets/inventories/weapons/Royal.png"),
    Sinister: require("@/assets/inventories/weapons/Sinister.png"),
    Stars: require("@/assets/inventories/weapons/Stars.png"),
    Sun: require("@/assets/inventories/weapons/Sun.png"),
    Wings: require("@/assets/inventories/weapons/Wings.png"),
  },
  [InventoryCategoryEnum.shield]: {
    Azure_Crystal_Shield: require("@/assets/inventories/shields/Azure_Crystal_Shield.png"),
    Bloodfang_Barrier: require("@/assets/inventories/shields/Bloodfang_Barrier.png"),
    Bloodthorn_Shield: require("@/assets/inventories/shields/Bloodthorn_Shield.png"),
    Crimson_Aegis: require("@/assets/inventories/shields/Crimson_Aegis.png"),
    Dawnbringer_Aegis: require("@/assets/inventories/shields/Dawnbringer_Aegis.png"),
    Dragonsbane_Aegis: require("@/assets/inventories/shields/Dragonsbane_Aegis.png"),
    Dragonscale_Ward: require("@/assets/inventories/shields/Dragonscale_Ward.png"),
    Emberfang_Bulwark: require("@/assets/inventories/shields/Emberfang_Bulwark.png"),
    Emberheart_Shield: require("@/assets/inventories/shields/Emberheart_Shield.png"),
    Emberstone_Guard: require("@/assets/inventories/shields/Emberstone_Guard.png"),
    Eternal_Ward: require("@/assets/inventories/shields/Eternal_Ward.png"),
    Flamebound_Ward: require("@/assets/inventories/shields/Flamebound_Ward.png"),
    Frostbite_Bulwark: require("@/assets/inventories/shields/Frostbite_Bulwark.png"),
    Frostfang_Bulwark: require("@/assets/inventories/shields/Frostfang_Bulwark.png"),
    Inferno_Barrier: require("@/assets/inventories/shields/Inferno_Barrier.png"),
    Ironwood_Protector: require("@/assets/inventories/shields/Ironwood_Protector.png"),
    Lioncrest_Guard: require("@/assets/inventories/shields/Lioncrest_Guard.png"),
    Moonlight_Aegis: require("@/assets/inventories/shields/Moonlight_Aegis.png"),
    Phoenixflame_Aegis: require("@/assets/inventories/shields/Phoenixflame_Aegis.png"),
    Shadowfang_Guard: require("@/assets/inventories/shields/Shadowfang_Guard.png"),
    Shadowplate_Guard: require("@/assets/inventories/shields/Shadowplate_Guard.png"),
    Skullfang_Bulwark: require("@/assets/inventories/shields/Skullfang_Bulwark.png"),
    Starforged_Bulwark: require("@/assets/inventories/shields/Starforged_Bulwark.png"),
    Stormbreaker_Shield: require("@/assets/inventories/shields/Stormbreaker_Shield.png"),
    Stormguard_Shield: require("@/assets/inventories/shields/Stormguard_Shield.png"),
    Sunfire_Barrier: require("@/assets/inventories/shields/Sunfire_Barrier.png"),
    Thunderheart_Shield: require("@/assets/inventories/shields/Thunderheart_Shield.png"),
    Titansteel_Guard: require("@/assets/inventories/shields/Titansteel_Guard.png"),
    Venomscale_Shield: require("@/assets/inventories/shields/Venomscale_Shield.png"),
    Verdant_Protector: require("@/assets/inventories/shields/Verdant_Protector.png"),
    Voidfang_Protector: require("@/assets/inventories/shields/Voidfang_Protector.png"),
    Wyrmfang_Guard: require("@/assets/inventories/shields/Wyrmfang_Guard.png"),
  },
  [InventoryCategoryEnum.body]: {
    Azure_Knight_Armor: require("@/assets/inventories/bodys/Azure_Knight_Armor.png"),
    Blizzard_Cuirass: require("@/assets/inventories/bodys/Blizzard_Cuirass.png"),
    Crystalplate_Armor: require("@/assets/inventories/bodys/Crystalplate_Armor.png"),
    Dawnfire_Armor: require("@/assets/inventories/bodys/Dawnfire_Armor.png"),
    Embersteel_Armor: require("@/assets/inventories/bodys/Embersteel_Armor.png"),
    Frostguard_Armor: require("@/assets/inventories/bodys/Frostguard_Armor.png"),
    Froststeel_Brigandine: require("@/assets/inventories/bodys/Froststeel_Brigandine.png"),
    Glacial_Plate: require("@/assets/inventories/bodys/Glacial_Plate.png"),
    Icebound_Plate: require("@/assets/inventories/bodys/Icebound_Plate.png"),
    Moonshade_Armor: require("@/assets/inventories/bodys/Moonshade_Armor.png"),
    Oceanborn_Armor: require("@/assets/inventories/bodys/Oceanborn_Armor.png"),
    Phantom_Shell: require("@/assets/inventories/bodys/Phantom_Shell.png"),
    Polar_Sentinel_Armor: require("@/assets/inventories/bodys/Polar_Sentinel_Armor.png"),
    Shadowhide_Armor: require("@/assets/inventories/bodys/Shadowhide_Armor.png"),
    Stonebark_Cuirass: require("@/assets/inventories/bodys/Stonebark_Cuirass.png"),
    Stormbreaker_Armor: require("@/assets/inventories/bodys/Stormbreaker_Armor.png"),
    Tempest_Armor: require("@/assets/inventories/bodys/Tempest_Armor.png"),
    Venomroot_Armor: require("@/assets/inventories/bodys/Venomroot_Armor.png"),
    Verdant_Scale_Armor: require("@/assets/inventories/bodys/Verdant_Scale_Armor.png"),
    Voidforged_Armor: require("@/assets/inventories/bodys/Voidforged_Armor.png"),
  },
  [InventoryCategoryEnum.head]: {
    Amethyst_Helm: require("@/assets/inventories/heads/Amethyst_Helm.png"),
    Bloodforge_Helm: require("@/assets/inventories/heads/Bloodforge_Helm.png"),
    Crystal_Hood: require("@/assets/inventories/heads/Crystal_Hood.png"),
    Dawnfire_Helmet: require("@/assets/inventories/heads/Dawnfire_Helmet.png"),
    Ember_Crown: require("@/assets/inventories/heads/Ember_Crown.png"),
    Eternal_Crown: require("@/assets/inventories/heads/Eternal_Crown.png"),
    Flameforged_Helmet: require("@/assets/inventories/heads/Flameforged_Helmet.png"),
    Froststeel_Helmet: require("@/assets/inventories/heads/Froststeel_Helmet.png"),
    Inferno_Crown: require("@/assets/inventories/heads/Inferno_Crown.png"),
    Ironfang_Helmet: require("@/assets/inventories/heads/Ironfang_Helmet.png"),
    Moonshadow_Helmet: require("@/assets/inventories/heads/Moonshadow_Helmet.png"),
    Phantom_Hood: require("@/assets/inventories/heads/Phantom_Hood.png"),
    Shadowguard_Helm: require("@/assets/inventories/heads/Shadowguard_Helm.png"),
    Sunfire_Circlet: require("@/assets/inventories/heads/Sunfire_Circlet.png"),
    Twilight_Hood: require("@/assets/inventories/heads/Twilight_Hood.png"),
    Venomscale_Helmet: require("@/assets/inventories/heads/Venomscale_Helmet.png"),
    Verdant_Circlet: require("@/assets/inventories/heads/Verdant_Circlet.png"),
    Void_Circlet: require("@/assets/inventories/heads/Void_Circlet.png"),
  },
  [InventoryCategoryEnum.jewelry]: {
    Amethyst_Trinity: require("@/assets/inventories/jewelrys/Amethyst_Trinity.png"),
    Azure_Wing_Emblem: require("@/assets/inventories/jewelrys/Azure_Wing_Emblem.png"),
    Crimson_Ruby_Staff: require("@/assets/inventories/jewelrys/Crimson_Ruby_Staff.png"),
    Emberstone_Pendant: require("@/assets/inventories/jewelrys/Emberstone_Pendant.png"),
    Eye_of_Eternity: require("@/assets/inventories/jewelrys/Eye_of_Eternity.png"),
    Heart_of_Flame: require("@/assets/inventories/jewelrys/Heart_of_Flame.png"),
    Oceanborn_Pendant: require("@/assets/inventories/jewelrys/Oceanborn_Pendant.png"),
    Scarab_Amulet: require("@/assets/inventories/jewelrys/Scarab_Amulet.png"),
    Serpentfang_Talisman: require("@/assets/inventories/jewelrys/Serpentfang_Talisman.png"),
    Sunspire_Talisman: require("@/assets/inventories/jewelrys/Sunspire_Talisman.png"),
    Verdant_Sigil: require("@/assets/inventories/jewelrys/Verdant_Sigil.png"),
  },
  [InventoryCategoryEnum.leg]: {
    Crystalweave_Pants: require("@/assets/inventories/legs/Crystalweave_Pants.png"),
    Dawnfire_Trousers: require("@/assets/inventories/legs/Dawnfire_Trousers.png"),
    Emberstride_Leggings: require("@/assets/inventories/legs/Emberstride_Leggings.png"),
    Flameforged_Greaves: require("@/assets/inventories/legs/Flameforged_Greaves.png"),
    Frostwoven_Pants: require("@/assets/inventories/legs/Frostwoven_Pants.png"),
    Ironbound_Legs: require("@/assets/inventories/legs/Ironbound_Legs.png"),
    Moonshade_Leggings: require("@/assets/inventories/legs/Moonshade_Leggings.png"),
    Phantomstride_Greaves: require("@/assets/inventories/legs/Phantomstride_Greaves.png"),
    Shadowstalker_Legs: require("@/assets/inventories/legs/Shadowstalker_Legs.png"),
    Stoneforged_Greaves: require("@/assets/inventories/legs/Stoneforged_Greaves.png"),
    Stormrider_Pants: require("@/assets/inventories/legs/Stormrider_Pants.png"),
    Venomscale_Trousers: require("@/assets/inventories/legs/Venomscale_Trousers.png"),
    Verdant_Path_Leggings: require("@/assets/inventories/legs/Verdant_Path_Leggings.png"),
  },
};
